# Generated by Django 4.0.1 on 2022-01-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Aluno')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=50, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('idplano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plano', verbose_name='idPlano')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
