# Generated by Django 4.0.1 on 2022-01-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_idplano'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do pagamento')),
            ],
            options={
                'verbose_name': 'Tipo de pagamento',
                'verbose_name_plural': 'Tipos de pagamento',
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valido_de', models.DateField(max_length=50, verbose_name='Válido de:')),
                ('valido_ate', models.DateField(max_length=50, verbose_name='Válido até:')),
                ('data_pagto', models.DateField(max_length=50, verbose_name='Data do pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8, max_length=50, verbose_name='Valor Pago')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno', verbose_name='Aluno')),
                ('tipo_pagto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopagto', verbose_name='Tipo Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
