# Generated by Django 4.0.1 on 2022-02-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipopagto_alter_aluno_cpf_alter_aluno_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idplano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plano', verbose_name='Plano'),
        ),
    ]
